//user login action's constants:::
export const userConstants = {
    REGISTER_REQUEST:'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE:'USER_REGISTER_FAILURE',

    LOGIN_REQUEST:'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE:'USER_LOGIN_FAILURE',
    CHECK_LOGIN_REQUEST:'USER_CHECK_LOGIN',
    CHECK_LOGIN_FAILURE:'USER_CHECK_LOGIN_FAILURE',

    LOGOUT:'USER_LOGOUT',

    ////DONT UNDERSTAND ACTION FORM EXAMPLE
}

export const IAFConstants = {
    MATCH_REQUEST:'FINANCE_MATCH_REQUEST',
    MATCH_SUCCESS:'FINANCE_MATCH_SUCCESS',
    MATCH_FAILURE:'FINANCE_MATCH_FAILURE',
}

export const graphDataConstants = {
    GET_DATA_REQUEST:'DATA_REQUEST',
    GET_DATA_SUCCESS:'GET_DATA_SUCCESS',
    GET_DATA_fAILURE:'GET_DATA_FAILURE'
}

