
//alert's constant:::
export const alertConstants = {
    SUCCESS:'ALERT_SUCCESS',
    ERROR:'ALERT_ERROR',
    CLEAR:'ALERT_CLEAR'
};

//user login action's constants:::
export const userConstants = {
    // REGISTER_REQUEST_INFO:'USERS_REGISTER_REQUEST_INFO',
    // REGISTER_SUCCESS_INFO:'USER_REGISTER_SUCCESS_INFO',
    // REGISTER_FAILURE_INFO:'USER_REGISTER_FAILURE',

    REGISTER_REQUEST:'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE:'USER_REGISTER_FAILURE',

    LOGIN_REQUEST:'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE:'USER_LOGIN_FAILURE',
    CHECK_LOGIN_REQUEST:'USER_CHECK_LOGIN',
    CHECK_LOGIN_FAILURE:'USER_CHECK_LOGIN_FAILURE',

    LOGOUT:'USER_LOGOUT',

    ////DONT UNDERSTAND ACTION FORM EXAMPLE
}

export const IAFConstants = {
    MATCH_REQUEST:'FINANCE_MATCH_REQUEST',
    MATCH_SUCCESS:'FINANCE_MATCH_SUCCESS',
    MATCH_FAILURE:'FINANCE_MATCH_FAILURE',
}

