
//alert's constant:::
export const alertConstants = {
    SUCCESS:'ALERT_SUCCESS',
    ERROR:'ALERT_ERROR',
    CLEAR:'ALERT_CLEAR'
};

//user login action's constants:::
export const userConstants = {
    REGISTER_REQUEST:'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE:'USER_REGISTER_FAILURE',

    LOGIN_REQUEST:'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE:'USER_LOGIN_FAILURE',
    CHECK_LOGIN_REQUEST:'USER_CHECK_LOGIN',

    LOGOUT:'USER_LOGOUT',

    ////DONT UNDERSTAND ACTION FORM EXAMPLE
    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'

}

export const IAFConstants = {
    MATCH_REQUEST:'FINANCE_MATCH_REQUEST',
    MATCH_SUCCESS:'FINANCE_MATCH_SUCCESS',
    MATCH_FAILURE:'FINANCE_MATCH_FAILURE',
}

export const getMonthRange = {
    GET_MONTH_RANGE:'GET_MONTH_RANGE',
}
